version: '3.8'

services:
  medical-imaging-ai:
    build:
      context: ./medical-imaging-ai
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - SERVICE_NAME=medical-imaging-ai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ai-diagnostics:
    build:
      context: ./ai-diagnostics
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - SERVICE_NAME=ai-diagnostics
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  genomic-intelligence:
    build:
      context: ./genomic-intelligence-service
      dockerfile: Dockerfile
    ports:
      - "5007:5007"
    environment:
      - SERVICE_NAME=genomic-intelligence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5007/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  obicare:
    build:
      context: ./phase4-services/obicare
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    environment:
      - SERVICE_NAME=obicare
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  hipaa-monitor:
    build:
      context: ./phase4-services/hipaa-monitor
      dockerfile: Dockerfile
    ports:
      - "5011:5011"
    environment:
      - SERVICE_NAME=hipaa-monitor
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5011/health"]
      interval: 30s
      timeout: 10s
      retries: 3
